//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMDatos.ORM.ForMySQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mymEntities : DbContext
    {
        public mymEntities()
            : base("name=mymEntities")
        {
        }

        public mymEntities(string CadenaConexionMySQL) : base(CadenaConexionMySQL)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mym_academia> mym_academia { get; set; }
        public DbSet<mym_cat_empresa> mym_cat_empresa { get; set; }
        public DbSet<mym_cat_estatus> mym_cat_estatus { get; set; }
        public DbSet<mym_cat_puesto> mym_cat_puesto { get; set; }
        public DbSet<mym_cat_tipo_academia> mym_cat_tipo_academia { get; set; }
        public DbSet<mym_cat_tipo_comunicacion> mym_cat_tipo_comunicacion { get; set; }
        public DbSet<mym_cat_tipo_direccion> mym_cat_tipo_direccion { get; set; }
        public DbSet<mym_cat_tipo_persona> mym_cat_tipo_persona { get; set; }
        public DbSet<mym_cat_titulo> mym_cat_titulo { get; set; }
        public DbSet<mym_comunicacion> mym_comunicacion { get; set; }
        public DbSet<mym_direccion> mym_direccion { get; set; }
        public DbSet<mym_experiencia_laboral> mym_experiencia_laboral { get; set; }
        public DbSet<mym_geo_ciudad> mym_geo_ciudad { get; set; }
        public DbSet<mym_geo_codigo_postal> mym_geo_codigo_postal { get; set; }
        public DbSet<mym_geo_estado> mym_geo_estado { get; set; }
        public DbSet<mym_geo_municipio> mym_geo_municipio { get; set; }
        public DbSet<mym_geo_pais> mym_geo_pais { get; set; }
        public DbSet<mym_persona> mym_persona { get; set; }
        public DbSet<mym_rel_persona_academia> mym_rel_persona_academia { get; set; }
        public DbSet<mym_rel_persona_comunicacion> mym_rel_persona_comunicacion { get; set; }
        public DbSet<mym_rel_persona_direccion> mym_rel_persona_direccion { get; set; }
        public DbSet<mym_rel_persona_exp_laboral> mym_rel_persona_exp_laboral { get; set; }
        public DbSet<mym_rel_persona_tipo_persona> mym_rel_persona_tipo_persona { get; set; }
    }
}
