//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMDatos.ORM.ForMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mym_persona
    {
        public mym_persona()
        {
            this.mym_rel_persona_academia = new HashSet<mym_rel_persona_academia>();
            this.mym_rel_persona_comunicacion = new HashSet<mym_rel_persona_comunicacion>();
            this.mym_rel_persona_direccion = new HashSet<mym_rel_persona_direccion>();
            this.mym_rel_persona_tipo_persona = new HashSet<mym_rel_persona_tipo_persona>();
            this.mym_rel_persona_exp_laboral = new HashSet<mym_rel_persona_exp_laboral>();
        }
    
        public System.Guid id { get; set; }
        public string nombre { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string sexo { get; set; }
        public string rfc { get; set; }
        public string curp { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> ultima_modificacion { get; set; }
        public string url_fotografia { get; set; }
        public int estatus { get; set; }
    
        public virtual ICollection<mym_rel_persona_academia> mym_rel_persona_academia { get; set; }
        public virtual ICollection<mym_rel_persona_comunicacion> mym_rel_persona_comunicacion { get; set; }
        public virtual ICollection<mym_rel_persona_direccion> mym_rel_persona_direccion { get; set; }
        public virtual ICollection<mym_rel_persona_tipo_persona> mym_rel_persona_tipo_persona { get; set; }
        public virtual ICollection<mym_rel_persona_exp_laboral> mym_rel_persona_exp_laboral { get; set; }
    }
}
