//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMDatos.ORM.ForMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mym_direccion
    {
        public mym_direccion()
        {
            this.mym_rel_persona_direccion = new HashSet<mym_rel_persona_direccion>();
        }
    
        public System.Guid id { get; set; }
        public int id_pais { get; set; }
        public int id_estado { get; set; }
        public int id_municipio { get; set; }
        public int id_ciudad { get; set; }
        public int id_codigo_postal { get; set; }
        public string calle { get; set; }
        public string no_ext { get; set; }
        public string no_int { get; set; }
        public int tipo_direccion { get; set; }
        public int estatus { get; set; }
    
        public virtual mym_cat_estatus mym_cat_estatus { get; set; }
        public virtual mym_cat_tipo_direccion mym_cat_tipo_direccion { get; set; }
        public virtual mym_geo_ciudad mym_geo_ciudad { get; set; }
        public virtual mym_geo_codigo_postal mym_geo_codigo_postal { get; set; }
        public virtual mym_geo_estado mym_geo_estado { get; set; }
        public virtual mym_geo_municipio mym_geo_municipio { get; set; }
        public virtual mym_geo_pais mym_geo_pais { get; set; }
        public virtual ICollection<mym_rel_persona_direccion> mym_rel_persona_direccion { get; set; }
    }
}
