//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMDatos.ORM.ForMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mym_rel_persona_tipo_persona
    {
        public int id { get; set; }
        public System.Guid id_persona { get; set; }
        public int id_tipo_persona { get; set; }
        public Nullable<System.DateTime> fecha_alta_relacion { get; set; }
        public Nullable<System.DateTime> ultima_modificacion { get; set; }
        public int estatus { get; set; }
    
        public virtual mym_cat_estatus mym_cat_estatus { get; set; }
        public virtual mym_cat_tipo_persona mym_cat_tipo_persona { get; set; }
        public virtual mym_persona mym_persona { get; set; }
    }
}
