//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMDatos.ORM.ForMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mym_experiencia_laboral
    {
        public mym_experiencia_laboral()
        {
            this.mym_rel_persona_exp_laboral = new HashSet<mym_rel_persona_exp_laboral>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid empresa_laboro { get; set; }
        public int puesto { get; set; }
        public System.DateTime fecha_entrada { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public decimal sueldo_entrada { get; set; }
        public decimal sueldo_salida { get; set; }
        public string descripcion_labores { get; set; }
        public string motivo_salida { get; set; }
        public string telefono_empresa { get; set; }
        public string jefe_inmediato { get; set; }
        public int estatus { get; set; }
    
        public virtual mym_cat_empresa mym_cat_empresa { get; set; }
        public virtual mym_cat_estatus mym_cat_estatus { get; set; }
        public virtual mym_cat_puesto mym_cat_puesto { get; set; }
        public virtual ICollection<mym_rel_persona_exp_laboral> mym_rel_persona_exp_laboral { get; set; }
    }
}
