//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMDatos.ORM.ForMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mym_cat_puesto
    {
        public mym_cat_puesto()
        {
            this.mym_experiencia_laboral = new HashSet<mym_experiencia_laboral>();
        }
    
        public int id { get; set; }
        public string puesto { get; set; }
        public string homologaciones { get; set; }
        public int estatus { get; set; }
    
        public virtual ICollection<mym_experiencia_laboral> mym_experiencia_laboral { get; set; }
    }
}
