//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMDatos.ORM.ForMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mym_comunicacion
    {
        public mym_comunicacion()
        {
            this.mym_rel_persona_comunicacion = new HashSet<mym_rel_persona_comunicacion>();
        }
    
        public System.Guid id { get; set; }
        public string descripcion { get; set; }
        public int tipo_comunicacion { get; set; }
        public int estatus { get; set; }
    
        public virtual mym_cat_estatus mym_cat_estatus { get; set; }
        public virtual mym_cat_tipo_comunicacion mym_cat_tipo_comunicacion { get; set; }
        public virtual ICollection<mym_rel_persona_comunicacion> mym_rel_persona_comunicacion { get; set; }
    }
}
