//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMDatos.ORM.ForMySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mym_cat_empresa
    {
        public mym_cat_empresa()
        {
            this.mym_experiencia_laboral = new HashSet<mym_experiencia_laboral>();
        }
    
        public System.Guid id { get; set; }
        public string nombre { get; set; }
        public string homologaciones { get; set; }
        public int estatus { get; set; }
    
        public virtual ICollection<mym_experiencia_laboral> mym_experiencia_laboral { get; set; }
    }
}
